name: deploy workflow
on: push
jobs:
  test_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.1
      - name: Install Dependencies 
        run: npm ci
      - name: Run esLint
        run: npm run lint
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.1
      - name: Install Dependencies 
        run: npm ci
      - name: Run Tests
        run: npm run test
  build:
    needs: [test_lint,run_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.1
      - name: Install Dependencies 
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: | 
          echo 'deploying ....'
          echo 'deployment complete!'
    
